version: '3.8'

services:
  app:
    build: ./app
    ports: 
      - "5002:5000"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
      - DB_HOST=db  
    depends_on:
      - db
    networks:
      - connection
  db:
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db 
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - connection

volumes:
  db_data:

networks:
  connection: